<?php
/**
 * @file
 * menu_link.ae637fbd333b0f5a24c51a7981ff47934dd150d6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'devel/node_access/summary',
  'link_title' => 'Node_access summary',
  'menu_name' => 'devel',
  'weight' => '0',
  'expanded' => '0',
  'options' => array(),
  'router_path' => 'devel/node_access/summary',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.devel' => 'menu.devel',
);

$optional = array();

$modules = array();
