<?php
/**
 * @file
 * menu_link.d7dbd6fb7c3e42cc42745d25c5e505e416e646c3.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'carers',
  'link_title' => 'Carers',
  'menu_name' => 'main-menu',
  'weight' => '-49',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'carers',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
