<?php
/**
 * @file
 * menu_link.54e9a7485086f239b3c357d56f19d7ce5f2cb8a6.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'jobs',
  'link_title' => 'Jobs',
  'menu_name' => 'main-menu',
  'weight' => '-48',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'jobs',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
