<?php
/**
 * @file
 * menu_link.51582537a1ad83b1774201b30f584210a559f72c.inc
 */

$api = '2.0.0';

$data = array(
  'link_path' => 'contact',
  'link_title' => 'Contact Us',
  'menu_name' => 'main-menu',
  'weight' => '-47',
  'expanded' => '0',
  'options' => array(
    'attributes' => array(
      'title' => '',
    ),
    'alter' => TRUE,
  ),
  'router_path' => 'contact',
  'parent_identifier' => NULL,
);

$dependencies = array(
  'menu.main_menu' => 'menu.main_menu',
);

$optional = array();

$modules = array();
