<?php

// This file contains the current being tracked configurations.

$tracked = array (
  'image_style.large_profile_photo' => 'fa02866516fde2966ff1cf839dc9f7334e4e98e4',
  'image_style.logo' => '607b48dfa45a83f0d05153cff6387c98c414cefe',
  'image_style.medium' => '09509362270b8ca744541897f738e11d8b1c8adb',
  'image_style.profile_photo' => 'b54cc56d4089b7c48156028658a7522aaf83bb75',
  'image_style.thumbnail' => 'c6647cdf51d1707346fe93462cce294f5d7cfe2d',
);


// The following modules are required to run the configurations of this file.

$modules = array(
  'image',
);
