<?php
/**
 * @file
 * variable.captcha_placement_map_cache.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'captcha_placement_map_cache',
  'content' => array(
    'contact_site_form' => array(
      'path' => array(),
      'key' => 'actions',
      'weight' => 99,
    ),
    'user_login' => array(
      'path' => array(),
      'key' => 'actions',
      'weight' => 99,
    ),
    'user_pass' => array(
      'path' => array(),
      'key' => 'actions',
      'weight' => 99,
    ),
    'user_register_form' => array(
      'path' => array(),
      'key' => 'actions',
      'weight' => 99,
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
