<?php
/**
 * @file
 * variable.html_title_allowed_elements.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'html_title_allowed_elements',
  'content' => array(
    'em' => 'em',
    'i' => 'i',
    'sub' => 'sub',
    'sup' => 'sup',
    'abbr' => 0,
    'b' => 0,
    'bdi' => 0,
    'cite' => 0,
    'code' => 0,
    'strong' => 0,
    'wbr' => 0,
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
