<?php
/**
 * @file
 * variable.theme_settings.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'theme_settings',
  'content' => array(
    'toggle_logo' => 1,
    'toggle_name' => 1,
    'toggle_slogan' => 1,
    'toggle_node_user_picture' => 1,
    'toggle_comment_user_picture' => 1,
    'toggle_comment_user_verification' => 1,
    'toggle_favicon' => 1,
    'toggle_main_menu' => 1,
    'toggle_secondary_menu' => 1,
    'default_logo' => 0,
    'logo_path' => 'public://signamic-logo-new_0.png',
    'default_favicon' => 1,
    'favicon_path' => '',
    'favicon_upload' => '',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
