<?php
/**
 * @file
 * variable.field_bundle_settings_privatemsg_message__privatemsg_message.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_privatemsg_message__privatemsg_message',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(
        'recipient' => array(
          'weight' => '3',
        ),
        'subject' => array(
          'weight' => '0',
        ),
        'body' => array(
          'weight' => '1',
        ),
        'token' => array(
          'weight' => '2',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
