<?php
/**
 * @file
 * variable.field_bundle_settings_profile2__agency.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_profile2__agency',
  'content' => array(
    'view_modes' => array(
      'page' => array(
        'custom_settings' => TRUE,
      ),
      'account' => array(
        'custom_settings' => FALSE,
      ),
      'teaser' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
      'carer_details_employer' => array(
        'custom_settings' => FALSE,
      ),
      'carer_profile' => array(
        'custom_settings' => FALSE,
      ),
      'employer_details_carer_' => array(
        'custom_settings' => FALSE,
      ),
      'agency' => array(
        'custom_settings' => TRUE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
