<?php
/**
 * @file
 * variable.locale_custom_strings_en.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'locale_custom_strings_en',
  'content' => array(
    '' => array(
      'A valid e-mail address. All e-mails from the system will be sent to this address. The e-mail address is not made public and will only be used if you wish to receive a new password or wish to receive certain news or notifications by e-mail.' => 'A valid e-mail address. All e-mails from the site will be sent to this address.',
      'Cancel Subscription' => 'Cancel Membership',
      'Create new account' => 'Register',
      'My Account' => 'Change Password/Email',
      'Subscriber' => 'Member',
      'Subscriber:' => 'Member:',
      'Subscription' => 'Membership',
      'Yes, Cancel Subscription' => 'Yes, Cancel Membership',
      'Your comment has been posted.' => 'Your reply has been sent.',
      'Are you sure you would like to cancel this subscription?' => 'Are you sure you would like to cancel this membership?',
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
