<?php
/**
 * @file
 * variable.entityreference_base_tables.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'entityreference:base-tables',
  'content' => array(
    'comment' => array(
      0 => 'comment',
      1 => 'cid',
    ),
    'flagging' => array(
      0 => 'flagging',
      1 => 'flagging_id',
    ),
    'node' => array(
      0 => 'node',
      1 => 'nid',
    ),
    'paragraphs_item' => array(
      0 => 'paragraphs_item',
      1 => 'item_id',
    ),
    'payment' => array(
      0 => 'payment',
      1 => 'pid',
    ),
    'payment_method' => array(
      0 => 'payment_method',
      1 => 'pmid',
    ),
    'profile2' => array(
      0 => 'profile',
      1 => 'pid',
    ),
    'profile2_type' => array(
      0 => 'profile_type',
      1 => 'id',
    ),
    'file' => array(
      0 => 'file_managed',
      1 => 'fid',
    ),
    'taxonomy_term' => array(
      0 => 'taxonomy_term_data',
      1 => 'tid',
    ),
    'taxonomy_vocabulary' => array(
      0 => 'taxonomy_vocabulary',
      1 => 'vid',
    ),
    'user' => array(
      0 => 'users',
      1 => 'uid',
    ),
    'rules_config' => array(
      0 => 'rules_config',
      1 => 'id',
    ),
    'menu_link' => array(
      0 => 'menu_links',
      1 => 'mlid',
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
