<?php
/**
 * @file
 * variable.googleanalytics_trackfiles_extensions.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'googleanalytics_trackfiles_extensions',
  'content' => '7z|aac|arc|arj|asf|asx|avi|bin|csv|doc(x|m)?|dot(x|m)?|exe|flv|gif|gz|gzip|hqx|jar|jpe?g|js|mp(2|3|4|e?g)|mov(ie)?|msi|msp|pdf|phps|png|ppt(x|m)?|pot(x|m)?|pps(x|m)?|ppam|sld(x|m)?|thmx|qtm?|ra(m|r)?|sea|sit|tar|tgz|torrent|txt|wav|wma|wmv|wpd|xls(x|m|b)?|xlt(x|m)|xlam|xml|z|zip',
);

$dependencies = array();

$optional = array();

$modules = array();
