<?php
/**
 * @file
 * variable.field_bundle_settings_ds_views__carers_page_fields.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_ds_views__carers-page-fields',
  'content' => array(
    'view_modes' => array(),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(
        'title' => array(
          'default' => array(
            'weight' => '19',
            'visible' => FALSE,
          ),
        ),
      ),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
