<?php
/**
 * @file
 * variable.default_field_group.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'default_field_group',
  'content' => array(
    'group_account_details|profile2|carer_employer|form' => FALSE,
    'group_cr_details|profile2|carer_employer|form' => FALSE,
    'group_representative|profile2|carer_employer|form' => FALSE,
    'group_account_details|profile2|carer_employer|default' => FALSE,
    'group_representative|profile2|carer_employer|default' => FALSE,
    'group_cr_details|profile2|carer_employer|default' => FALSE,
    'group_agency|node|job|form' => FALSE,
    'group_work|profile2|carer|form' => FALSE,
    'group_personal|profile2|carer|form' => FALSE,
    'group_accordion|profile2|carer|form' => FALSE,
    'group_experience|profile2|carer|form' => FALSE,
    'group_carer_work|profile2|carer|form' => FALSE,
    'group_carer_personal_details|profile2|carer|default' => FALSE,
    'group_carer_work_details|profile2|carer|default' => FALSE,
    'group_employment_history|profile2|carer|default' => FALSE,
    'group_carer_qualifications|profile2|carer|default' => FALSE,
    'group_carer_work_preferences|profile2|carer|default' => FALSE,
    'group_personal|profile2|carer|page' => FALSE,
    'group_work|profile2|carer|page' => FALSE,
    'group_qualifications|profile2|carer|page' => FALSE,
    'group_work_experience|profile2|carer|page' => FALSE,
    'group_personal|profile2|carer|carer_profile' => FALSE,
    'group_personal|profile2|carer|carer_details_employer' => FALSE,
    'group_work|profile2|carer|carer_details_employer' => FALSE,
    'group_qualifications|profile2|carer|carer_details_employer' => FALSE,
    'group_experience|profile2|carer|carer_details_employer' => FALSE,
    'group_work_experience|profile2|carer|carer_details_employer' => TRUE,
    'group_top_bar|profile2|carer|carer_details_employer' => TRUE,
    'group_job|node|job|full' => FALSE,
    'group_job|node|job|job_details_carer' => FALSE,
    'group_cr_details|profile2|carer_employer|employer_details_carer_' => FALSE,
    'group_care_receiver|node|job|job_details_carer' => FALSE,
    'group_message|node|message|full' => FALSE,
    'group_job|node|job|job_details_agency_' => FALSE,
    'group_agency|node|job|job_details_agency_' => FALSE,
    'group_job|node|job|job_details_agency_view' => FALSE,
    'group_agency|node|job|job_details_agency_view' => FALSE,
    'group_left|node|job|job_details_agency_view' => FALSE,
    'group_right|node|job|job_details_agency_view' => FALSE,
    'group_left|node|job|job_details_agency_' => FALSE,
    'group_right|node|job|job_details_agency_' => FALSE,
    'group_left|node|job|job_details_carer' => FALSE,
    'group_right|node|job|job_details_carer' => FALSE,
    'group_left|node|job|full' => FALSE,
    'group_right|node|job|full' => FALSE,
    'group_details|profile2|agency|page' => FALSE,
    'group_agency_details|profile2|agency|agency' => FALSE,
    'group_title_wrapper|node|page|default' => FALSE,
    'group_top|node|job|job_details_agency_view' => FALSE,
    'group_top|node|job|job_details_carer' => FALSE,
    'group_top|node|job|job_details_agency_' => FALSE,
    'group_top|profile2|carer|carer_details_employer' => FALSE,
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
