<?php
/**
 * @file
 * variable.submitted_by_message.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'submitted_by_message',
  'content' => array(
    'full' => 'Submitted by [node:author] on [node:created]',
    'teaser' => 'Submitted by [node:author] on [node:created]',
    'rss' => 'Submitted by [node:author] on [node:created]',
    'search_index' => 'Submitted by [node:author] on [node:created]',
    'search_result' => 'Submitted by [node:author] on [node:created]',
    'token' => 'Submitted by [node:author] on [node:created]',
    'job_details_carer' => 'Submitted by [node:author] on [node:created]',
    'revision' => 'Submitted by [node:author] on [node:created]',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
