<?php
/**
 * @file
 * variable.field_bundle_settings_comment__comment_node_message.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_comment__comment_node_message',
  'content' => array(
    'view_modes' => array(
      'full' => array(
        'custom_settings' => TRUE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
