<?php
/**
 * @file
 * variable.menu_default_active_menus.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'menu_default_active_menus',
  'content' => array(
    0 => 'menu-agency-menu',
    1 => 'menu-carers',
    2 => 'devel',
    3 => 'menu-employers-menu',
    5 => 'main-menu',
    6 => 'management',
    7 => 'navigation',
    8 => 'user-menu',
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
