<?php
/**
 * @file
 * variable.module_filter_recent_modules.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'module_filter_recent_modules',
  'content' => array(
    'legal' => 1470413457,
    'views_litepager' => 1470670881,
    'admin_devel' => 1470414790,
    'devel' => 1470751376,
    'devel_generate' => 1470414790,
    'devel_node_access' => 1470414790,
    'transliteration' => 1470473809,
    'googleanalytics' => 1470751015,
    'xmlsitemap' => 1470751666,
    'xmlsitemap_menu' => 1470751666,
    'xmlsitemap_node' => 1470751666,
    'xmlsitemap_custom' => 1470752629,
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
