<?php
/**
 * @file
 * variable.field_bundle_settings_node__page.inc
 */

$api = '2.0.0';

$data = array(
  'name' => 'field_bundle_settings_node__page',
  'content' => array(
    'view_modes' => array(
      'teaser' => array(
        'custom_settings' => TRUE,
      ),
      'full' => array(
        'custom_settings' => FALSE,
      ),
      'rss' => array(
        'custom_settings' => FALSE,
      ),
      'search_index' => array(
        'custom_settings' => FALSE,
      ),
      'search_result' => array(
        'custom_settings' => FALSE,
      ),
      'token' => array(
        'custom_settings' => FALSE,
      ),
      'agency_membership' => array(
        'custom_settings' => FALSE,
      ),
      'job_details_agency_' => array(
        'custom_settings' => FALSE,
      ),
      'job_details_agency_view' => array(
        'custom_settings' => FALSE,
      ),
      'job_details_carer' => array(
        'custom_settings' => FALSE,
      ),
      'revision' => array(
        'custom_settings' => FALSE,
      ),
    ),
    'extra_fields' => array(
      'form' => array(
        'title' => array(
          'weight' => '-5',
        ),
        'path' => array(
          'weight' => '30',
        ),
        'metatags' => array(
          'weight' => '40',
        ),
      ),
      'display' => array(),
    ),
  ),
);

$dependencies = array();

$optional = array();

$modules = array();
